pipeline {
    agent any
    stages {
        stage('Hello') {
            steps {
                script {
                    def scannerHome = tool 'sonarqube4_7';
                    withSonarQubeEnv('sonar') {

                      sh "ls ${scannerHome}/bin/sonar-scanner"
                    }
                }

            }
        }
    }
    post {
        success {
            sh "ls -l ./reports"
            junit '**/reports/*.xml'
        }
   }
}