pipeline {
    agent { docker { image 'python:3.9.1' } }
    stages {
        stage('Build') {
            steps {
                sh 'pip install -r requirements.txt'
                sh 'python -m pytest --cov-report term --cov=./ tests/'
                stash(name: 'compiled-results', includes: '*.py*')
            }
        }
    }
}